FROM java:latest

COPY ./target/reading.is.good-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch reading.is.good-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","reading.is.good-0.0.1-SNAPSHOT.jar "]
